# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a001fab138f90107dd1278ad8620a5ca11bf72efd8b0f4e9b2da4f86f320a55788f7c6605596a9084b1b985f4785e5fc347cafafa984d0417beeae251f46bf40

test:
  secret_key_base: 1cff3df5f2bc06b39f9d2b9140c1a40ccaaa968a4ce30a865be9f2043747fdfa17bd22869acad432fde46bcf47e79b690cb718daab93e0d8e49c684d490298a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
